Start verifying existence of secrets set...

diff --git a/.github/workflows/distribute.yml b/.github/workflows/distribute.yml
--- a/.github/workflows/distribute.yml
+++ b/.github/workflows/distribute.yml
@@ -20,11 +20,17 @@ jobs:
           echo "${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}" | base64 -d > android/app/google-services.json
       - name: Decode Keystore
         run: |
-          tempfile=$(mktemp)
-          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > "$tempfile"
-          touch keystore.jks
-          cat "$tempfile" >> keystore.jks
-          rm "$tempfile"
+          if [[ -z "${{ secrets.KEYSTORE_BASE64 }}" ]]; then
+            echo "::error::KEYSTORE_BASE64 secret is not defined."
+        #exit 1
+        #fi
+          else
+            tempfile=$(mktemp)
+            echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > "$tempfile"
+            touch keystore.jks
+            cat "$tempfile" >> keystore.jks
+            rm "$tempfile"
+          fi
       #echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > /home/runner/work/flutter_mvvm_mobx_github/flutter_mvvm_mobx_github/keystore.jks
       - name: Generate local.properties
         run: |
@@ -40,17 +46,47 @@ jobs:
         run: ls -la ./android
       - name: Set up Base64 Encoded Value
         run: echo "MY_ENCODED_VARIABLE=VEVTVF9TRUNSRVQK" >> $GITHUB_ENV
+      - name: Verify set secret variables...
+        run: |
+          if [[ -z "${{ secrets.FIREBASE_API_KEY }}" ]]; then
+            echo "::error::FIREBASE_API_KEY secret is not defined."
+            exit 1
+          fi
+          if [[ -z "${{ secrets.FIREBASE_APP_ID }}" ]]; then
+            echo "::error::FIREBASE_APP_ID secret is not defined."
+            exit 1
+          fi
+          if [[ -z "${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}" ]]; then
+            echo "::error::GOOGLE_SERVICES_JSON_BASE64 secret is not defined."
+            exit 1
+          fi
+          if [[ -z "${{ secrets.KEYSTORE_BASE64 }}" ]]; then
+            echo "::error::KEYSTORE_BASE64 secret is not defined."
+            exit 1
+          fi
+          if [[ -z "${{ secrets.KEYSTORE_PASSWORD }}" ]]; then
+            echo "::error::KEYSTORE_PASSWORD secret is not defined."
+            exit 1
+          fi
+          if [[ -z "${{ secrets.KEY_ALIAS }}" ]]; then
+            echo "::error::KEY_ALIAS secret is not defined."
+            exit 1
+          fi
+          if [[ -z "${{ secrets.KEY_PASSWORD }}" ]]; then
+            echo "::error::KEY_PASSWORD secret is not defined."
+            exit 1
+          fi
       - name: Set up environment variables
         run: |
           echo "FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }}" >> $GITHUB_ENV
           echo "FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID }}" >> $GITHUB_ENV
-          echo "FIREBASE_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}" >> $GITHUB_ENV
+        #echo "FIREBASE_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}" >> $GITHUB_ENV
           echo "KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> $GITHUB_ENV
           echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> $GITHUB_ENV
           echo "KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> $GITHUB_ENV
           echo "KEYSTORE_BASE64=${{ secrets.KEYSTORE_BASE64 }}" >> $GITHUB_ENV
-          echo "TEST_SECRET_BASE64=${{ secrets.TEST_SECRET_BASE64 }}" >> $GITHUB_ENV
-          echo "Decoded value: $(echo ${{ secrets.TEST_SECRET_BASE64 }} | base64 --decode)"
+        #echo "TEST_SECRET_BASE64=${{ secrets.TEST_SECRET_BASE64 }}" >> $GITHUB_ENV
+        #echo "Decoded value: $(echo ${{ secrets.TEST_SECRET_BASE64 }} | base64 --decode)"
           echo "::add-mask::${{ secrets.KEY_PASSWORD }}"
           source $GITHUB_ENV
       # ... other steps
@@ -112,7 +148,8 @@ jobs:
 
       # ... other build steps
       - name: Build debug AAB
-        run: flutter build appbundle --release --verbose --dart-define=FIREBASE_API_KEY="${{ secrets.FIREBASE_API_KEY }}" --dart-define=FIREBASE_APP_ID="${{ secrets.FIREBASE_APP_ID }}" --dart-define=FIREBASE_MESSAGING_SENDER_ID="${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}" --dart-define=KEYSTORE_PASSWORD="${{ secrets.KEYSTORE_PASSWORD }}" --dart-define=KEY_ALIAS="${{ secrets.KEY_ALIAS }}" --dart-define=KEY_PASSWORD="${{ secrets.KEY_PASSWORD }}" --dart-define=KEYSTORE_BASE64="${{ secrets.KEYSTORE_BASE64 }}"
+        run: flutter build appbundle --release --verbose --dart-define=FIREBASE_API_KEY="${{ secrets.FIREBASE_API_KEY }}" --dart-define=FIREBASE_APP_ID="${{ secrets.FIREBASE_APP_ID }}" --dart-define=KEYSTORE_PASSWORD="${{ secrets.KEYSTORE_PASSWORD }}" --dart-define=KEY_ALIAS="${{ secrets.KEY_ALIAS }}" --dart-define=KEY_PASSWORD="${{ secrets.KEY_PASSWORD }}" --dart-define=KEYSTORE_BASE64="${{ secrets.KEYSTORE_BASE64 }}"
+#        run: flutter build appbundle --release --verbose --dart-define=FIREBASE_API_KEY="${{ secrets.FIREBASE_API_KEY }}" --dart-define=FIREBASE_APP_ID="${{ secrets.FIREBASE_APP_ID }}" --dart-define=FIREBASE_MESSAGING_SENDER_ID="${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}" --dart-define=KEYSTORE_PASSWORD="${{ secrets.KEYSTORE_PASSWORD }}" --dart-define=KEY_ALIAS="${{ secrets.KEY_ALIAS }}" --dart-define=KEY_PASSWORD="${{ secrets.KEY_PASSWORD }}" --dart-define=KEYSTORE_BASE64="${{ secrets.KEYSTORE_BASE64 }}"
         #run: flutter build appbundle --profile --verbose --dart-define=FIREBASE_API_KEY="${{ secrets.FIREBASE_API_KEY }}" --dart-define=FIREBASE_APP_ID="${{ secrets.FIREBASE_APP_ID }}" --dart-define=FIREBASE_MESSAGING_SENDER_ID="${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}" --dart-define=KEYSTORE_PASSWORD="${{ secrets.KEYSTORE_PASSWORD }}" --dart-define=KEY_ALIAS="${{ secrets.KEY_ALIAS }}" --dart-define=KEY_PASSWORD="${{ secrets.KEY_PASSWORD }}" --dart-define=KEYSTORE_BASE64="${{ secrets.KEYSTORE_BASE64 }}"
         #run: flutter build appbundle --release --verbose
         #run: flutter build bundle --release --verbose
