Trying to fix verifying existence of secrets set...

diff --git a/.github/workflows/distribute.yml b/.github/workflows/distribute.yml
--- a/.github/workflows/distribute.yml
+++ b/.github/workflows/distribute.yml
@@ -13,12 +13,13 @@ jobs:
       - uses: actions/checkout@v3
       - name: Create google-services.json file
         run: |
-          if [[ -z "${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}" ]]; then
-            echo "::error::GOOGLE_SERVICES_JSON_BASE64 secret is not defined."
-            exit 1
-          else
-            echo "${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}" | base64 -d > android/app/google-services.json
-          fi
+          echo "${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}" | base64 -d > android/app/google-services.json
+#          if [[ -z "${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}" ]]; then
+#            echo "::error::GOOGLE_SERVICES_JSON_BASE64 secret is not defined."
+#            exit 1
+#          else
+#            echo "${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}" | base64 -d > android/app/google-services.json
+#          fi
       - name: Decode Keystore
         run: |
       #if [[ -z "${{ secrets.KEYSTORE_BASE64 }}" ]]; then
