Trying to fix verifying existence of secrets set...

diff --git a/.github/workflows/distribute.yml b/.github/workflows/distribute.yml
--- a/.github/workflows/distribute.yml
+++ b/.github/workflows/distribute.yml
@@ -14,12 +14,12 @@ jobs:
       - name: Create google-services.json file
         run: |
           echo "${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}" | base64 -d > android/app/google-services.json
-#          if [[ -z "${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}" ]]; then
-#            echo "::error::GOOGLE_SERVICES_JSON_BASE64 secret is not defined."
-#            exit 1
-#          else
-#            echo "${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}" | base64 -d > android/app/google-services.json
-#          fi
+      #          if [[ -z "${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}" ]]; then
+      #            echo "::error::GOOGLE_SERVICES_JSON_BASE64 secret is not defined."
+      #            exit 1
+      #          else
+      #            echo "${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}" | base64 -d > android/app/google-services.json
+      #          fi
       - name: Decode Keystore
         run: |
       #if [[ -z "${{ secrets.KEYSTORE_BASE64 }}" ]]; then
