Start verifying existence of secrets...

diff --git a/.github/workflows/distribute.yml b/.github/workflows/distribute.yml
--- a/.github/workflows/distribute.yml
+++ b/.github/workflows/distribute.yml
@@ -13,6 +13,10 @@ jobs:
       - uses: actions/checkout@v3
       - name: Create google-services.json file
         run: |
+          if [[ -z "${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}" ]]; then
+            echo "::error::GOOGLE_SERVICES_JSON_BASE64 secret is not defined."
+            exit 1
+          fi
           echo "${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}" | base64 -d > android/app/google-services.json
       - name: Decode Keystore
         run: |
